### ISSUE TITLE
Run_pin 22, i am confused

### ISSUE THREAD

**Issue by nictoglobe** [joba-1/PicoW_A2DP#4]
Hi

in the code you are setting RUN_PIN = 22, although commented. According to my understanding the RUN pin is 30 . So I am confused.What did you mean with this?

Regards

Andreas

**Comment by joba-1** [comment]
the name is a bit unfortunate. 
It is the pin I physically connect with the run pin to hard reset the pico from software.

**Comment by nictoglobe** [comment]
Mmm, i have a run button on my devboard which is soft resetting . It is pin 30. So how to use that with your code? Can I just pull pin 30 low?

Andreas

**Comment by nictoglobe** [comment]
![IMG_0685](https://github.com/joba-1/PicoW_A2DP/assets/85753936/6ee34621-7e83-4d9c-bea5-5528f76f0ad8)

**Comment by nictoglobe** [comment]
Hi, I just forget about pin 30, added my I2S pin nrs, compiled and perfect sound ! All works, thank you!

**Comment by joba-1** [comment]
it is an optional feature as you found out.

yes it works by pulling run(30)pin low (equivalent to your sw1)

you can still use it by connecting an io pin (i used 22) to the run(30)pin.

why use it? I was not sure if a software reset will fully reset and recover from everything (on an esp8266 it does not) So pulling run low is the sledgehammer method that always works.
